spring.application.name=customer-form-hub
spring.datasource.url=jdbc:mysql://localhost:3306/formhub
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true